name: Debug Python Versions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Python Versions
      run: curl -s https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json | jq .

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Verify Python Version
      run: python --version

    - name: Print Hello World
      run: echo "Hello World from Python 3.9"
